### PR TITLE
Add login domain httpapi param

### PR DESCRIPTION
**Pull request by mtarking**
Adding param to connection.yaml in prep for support in collection to support different domains for current and future versions of NDFC.

### CODE REVIEW

**Review by juburnet — APPROVED** [review]
Approved

**Review by devegupt — APPROVED** [review]
Looks good and executed a test successfully.

**Comment by juburnet** [comment]
> Do we want to update the robot tests as well to support the domain variable in the ndfc_common.resources
> 
> *** Variables *** ${login_json} {"domain" : "%{ND_DOMAIN=local}", "userName" : "%{ND_USERNAME}", "userPasswd" : "%{ND_PASSWORD}"}

@mtarking  - Since we will need to change this for Robot also, should we just use the same naming convention everywhere?  Perhaps we use ND_DOMAIN in all locations and users could also keep it as an environment var, similar to what we have for ND_USERNAME, etc.   The we can also keep local as the default everywhere as a backup if not provided.

**Review by devegupt — APPROVED** [review]
Executed tests successfully with setting up a new domain in the NDFC and then exporting correct and incorrect domain name for the new environment variable.

**Pull request merged**
